builds:
- id: lilmon
  binary: lilmon
  env:
    - CGO_ENABLED=1
  targets:
    - "linux_amd64"
    - "openbsd_amd64"
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
checksum:
  algorithm: sha256
  name_template: "checksums.txt"
